version: '3'
services:

  db:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - DOCKER_UID
      - DOCKER_GID


volumes:
  db-data:
