version: '3'
services:

  db:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # app:
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: ./docker/app.Dockerfile
  #   volumes:
  #     - .:/usr/src/app
  #   environment:
  #     - DOCKER_UID
  #     - DOCKER_GID
  #   ports:
  #     - "8000"
  #     - "8090"


volumes:
  db-data:
